export const monofazedSystems = [
  {
    putere: "3.48 kW Monofazat Hybrid Victron",
    invertor: "Multiplus 5000",
    panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
    stocare: "10.2 kW",
    numar: "8",
    pret: "6.000 lei",
    monofazat: true,
  },
  {
    putere: "4.35 kW Monofazat Hybrid Victron",
    invertor: "Multiplus 5000",
    panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
    stocare: "10.2 kW",
    numar: "10",
    pret: "7.000 lei",
    monofazat: true,
  },
  {
    putere: "5.22 kW Monofazat Hybrid Victron",
    invertor: "Multiplus 5000",
    panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
    stocare: "10.2 kW",
    numar: "12",
    pret: "8.000 lei",
    monofazat: true,
  },
  {
    putere: "6.09 kW Monofazat Hybrid Victron",
    invertor: "Multiplus 5000",
    panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
    stocare: "10.2 kW",
    numar: "14",
    pret: "9.000 lei",
    monofazat: true,
  },
  {
    putere: "6.52 kW Monofazat Hybrid Victron",
    invertor: "Multiplus 5000",
    panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
    stocare: "10.2 kW",
    numar: "15",
    pret: "9.500 lei",
    monofazat: true,
  },
    {
      putere: "3.48 kW Monofazat",
      invertor: "Solis/Solplanet 5 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "8",
      pret: "3.000 lei",
      monofazat: true,
    },
    {
      putere: "4.35 kW Monofazat",
      invertor: "Solis/Solplanet 5 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "10",
      pret: "3.000 lei",
      monofazat: true,
    },
    {
      putere: "5.22 kW Monofazat",
      invertor: "Solis/Solplanet 5 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "12",
      pret: "3.000 lei",
      monofazat: true,
    },
    {
      putere: "6.09 kW Monofazat",
      invertor: "Solis/Solplanet 6 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "14",
      pret: "4.000 lei",
      monofazat: true,
    },
    {
      putere: "6.96 kW Monofazat",
      invertor: "Solis/Solplanet 6 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "16",
      pret: "5.000 lei",
      monofazat: true,
    },
    {
      putere: "7.83 kW Monofazat",
      invertor: "Solis/Solplanet 6 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "18",
      pret: "6.000 lei",
      monofazat: true,
    },
    {
      putere: "8.70 kW Monofazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "20",
      pret: "7.000 lei",
      monofazat: true,
    },
    {
      putere: "9.57 kW Monofazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "22",
      pret: "8.000 lei",
      monofazat: true,
    },
    {
      putere: "10.44 kW Monofazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "24",
      pret: "9.000 lei",
      monofazat: true,
    },
  ];
  
 export const trifazedSystems = [
    {
      putere: "5.22 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "12",
      pret: "5.500 lei",
      monofazat: false,
    },
    {
      putere: "6.09 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "14",
      pret: "6.500 lei",
      monofazat: false,
    },
    {
      putere: "6.96 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "16",
      pret: "7.500 lei",
      monofazat: false,
    },
    {
      putere: "7.83 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "18",
      pret: "8.500 lei",
      monofazat: false,
    },
    {
      putere: "8.70 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "20",
      pret: "9.500 lei",
      monofazat: false,
    },
    {
      putere: "9.57 kW Trifazat",
      invertor: "Solis 8 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "22",
      pret: "10.500 lei",
      monofazat: false,
    },
    {
      putere: "10.44 kW Trifazat",
      invertor: "Solis 10 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "24",
      pret: "11.500 lei",
      monofazat: false,
    },
    {
      putere: "11.31 kW Trifazat",
      invertor: "Solis 10 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "26",
      pret: "12.500 lei",
      monofazat: false,
    },
    {
      putere: "12.18 kW Trifazat",
      invertor: "Solis 10 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "28",
      pret: "13.500 lei",
      monofazat: false,
    },
    {
      putere: "13.05 kW Trifazat",
      invertor: "Solis 12 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "30",
      pret: "14.500 lei",
      monofazat: false,
    },
    {
      putere: "13.92 kW Trifazat",
      invertor: "Solis 12 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "32",
      pret: "15.500 lei",
      monofazat: false,
    },
    {
      putere: "14.97 kW Trifazat",
      invertor: "Solis 12 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "34",
      pret: "16.500 lei",
      monofazat: false,
    },
    {
      putere: "15.66 kW Trifazat",
      invertor: "Solis 15 kW",
      panouri: "Canadian Solar TOPHiKu6 435 W N-Type",
      stocare: "10.2 kW",
      numar: "36",
      pret: "17.500 lei",
      monofazat: false,
    },
  ];
  